version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ports:
      - "3307:3306"
    volumes:
      - ./dados_mysql:/var/lib/mysql
    networks:
      - analytics
  worker:
    image: worker
    build:
      context: worker/.
      dockerfile: Dockerfile
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: mysql
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
    depends_on:
      - mysql
    networks:
      - analytics
networks: 
  analytics:
    driver: bridge